#!/bin/bash
~/.config/.screenlayout.sh

feh --bg-scale ~/.config/black_waves.jpg

setxkbmap -layout us,ru -option grp:win_space_toggle

xinput --set-prop 8 "libinput Accel Speed" -0.7 # for 1st mouse dpi
# xinput --set-prop 9 "libinput Accel Speed" -0.6 # for 2nd mouse dpi 

xrandr --output DP-1 --mode 2560x1440 --rate 165
xrandr --output HDMI-1 --gamma 1.0:1.0:1.0 --brightness 1.0

