#!/bin/bash

feh --bg-scale Downloads/20285447_6227297.jpg

setxkbmap -layout us,ru -option grp:win_space_toggle

xinput --set-prop 8 "libinput Accel Speed" -0.7

xrandr --output DisplayPort-0 --mode 2560x1440 --rate 165
